#!/usr/bin/tcsh

module purge

module load PrgEnv-amd
module load craype-accel-amd-gfx90a rocm
module load cmake

module list

unsetenv MPI_ROOT

setenv PE_MPICH_GTL_DIR_amd_gfx90a "-L${CRAY_MPICH_ROOTDIR}/gtl/lib"
setenv PE_MPICH_GTL_LIBS_amd_gfx90a "-lmpi_gtl_hsa"

setenv CRAY_CPU_TARGET "x86-64"

rm -rf build_crusher_amd
mkdir build_crusher_amd
cd build_crusher_amd

cmake -DOMPTGT=ON -DAMD=ON ../

make -j 16

