#!/usr/bin/tcsh

module purge

module load PrgEnv-cray
module load craype-accel-amd-gfx90a rocm
module load cmake

module list

unsetenv MPI_ROOT

setenv PE_MPICH_GTL_DIR_amd_gfx90a "-L${CRAY_MPICH_ROOTDIR}/gtl/lib"
setenv PE_MPICH_GTL_LIBS_amd_gfx90a "-lmpi_gtl_hsa"

setenv CRAY_CPU_TARGET "x86-64"

rm -rf build_crusher
mkdir build_crusher
cd build_crusher

cmake -DOMPTGT=ON ../

make -j 16

