set(CTEST_PROJECT_NAME "GronOR")
set(CTEST_NIGHTLY_START_TIME "05:00:00 America/New_Yrok")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "my.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=GronOR")
set(CTEST_DROP_SITE_CDASH TRUE)
