#!/usr/bin/tcsh

module load nvhpc mpich cmake

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx
unsetenv MPI_ROOT

rm -rf build
mkdir build
cd build

cmake -DOPENACC=ON -DCUSOLVERJ=ON -DOPENMP=ON ../

make -j 12

