#!/usr/bin/tcsh

module load intel mpich cmake utils

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx
unsetenv MPI_ROOT

env | grep MKL
env | grep UTILS

rm -rf build
mkdir build
cd build

cmake -DOPENMP=ON ../

make -j 12

