#!/usr/bin/tcsh

module load cmake
module load spectrum-mpi
module load cuda
module load pgi

module list

unsetenv MPI_ROOT

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx

rm -rf build
mkdir build
cd build

cmake FC=mpif90 CC=mpicc CXX=mpicxx -DOPENACC=ON -DCUSOLVERJ=ON ../

make -j 16
