#!/usr/bin/tcsh

module load PrgEnv-cray-amd
module load craype-accel-amd-gfx90a
module load cpe/24.11
module load rocm/6.3.1

module load cmake
module unload darshan-runtime

module list

setenv LD_LIBRARY_PATH ${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}

rm -rf build_frontier
mkdir build_frontier
cd build_frontier

if(! $?SOFTWARE ) setenv SOFTWARE $HOME/Software

cmake -DTARGET=FRONTIER -DOMPTGT=ON -DGPU=AMD -DLAPACK=ON -DROCSOLVER=ON -DCMAKE_INSTALL_PREFIX=$SOFTWARE/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../ 

make -j 16

make install
