#!/usr/bin/tcsh

#module load PrgEnv-cray-amd
module load craype-accel-amd-gfx90a
module load cpe/23.12
module load rocm/5.7.1
module load cmake
module unload darshan-runtime
module use /autofs/nccs-svm1_sw/crusher/amdsw/modules

#module load omniperf
#module load perftools

module list

#setenv OLCF_HIPFORT_ROOT /lustre/orion/world-shared/stf006/reubendb/sw/frontier/hipfort/cce_15.0.1-rocm_5.3.0
#setenv PE_MPICH_GTL_DIR_amd_gfx90a "-L${CRAY_MPICH_ROOTDIR}/gtl/lib"
#setenv PE_MPICH_GTL_LIBS_amd_gfx90a "-lmpi_gtl_hsa"

setenv LD_LIBRARY_PATH ${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}

rm -rf build_frontier
mkdir build_frontier
cd build_frontier

cmake -DTARGET=FRONTIER -DOMPTGT=ON -DLAPACK=ON -DCMAKE_INSTALL_PREFIX=/lustre/orion/proj-shared/chm154/Software/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../ 

make -j 16

make install
