#!/usr/bin/tcsh

module load PrgEnv-cray-amd
module load craype-accel-amd-gfx90a
module load cpe/23.12
module load rocm

module load cmake
module unload darshan-runtime

module list

#setenv PE_MPICH_GTL_DIR_amd_gfx90a "-L${CRAY_MPICH_ROOTDIR}/gtl/lib"
#setenv PE_MPICH_GTL_LIBS_amd_gfx90a "-lmpi_gtl_hsa"
#setenv LD_PRELOAD "/opt/cray/pe/cce/15.0.0/cce/x86_64/lib/libtcmalloc_minimal.so.1.0"
#setenv CRAY_CPU_TARGET "x86-64"
#setenv LD_LIBRARY_PATH ${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}

#setenv LD_LIBRARY_PATH ${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}

rm -rf build_frontier
mkdir build_frontier
cd build_frontier

if(! $?SOFTWARE ) setenv SOFTWARE $HOME/Software

#cmake -DTARGET=FRONTIER -DOMPTGT=ON -DLAPACK=ON -DHIPSOLVER=ON -DCMAKE_INSTALL_PREFIX=$SOFTWARE/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../ 
#cmake -DTARGET=FRONTIER -DOMPTGT=ON -DLAPACK=ON -DROCSOLVER=ON -DCMAKE_INSTALL_PREFIX=$SOFTWARE/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../ 
cmake -DTARGET=FRONTIER -DOMPTGT=ON -DLAPACK=ON -DCMAKE_INSTALL_PREFIX=$SOFTWARE/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../ 

make -j 16

make install
