#!/usr/bin/tcsh

module load nvhpc mpich cmake/3.22.3 utils

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx
unsetenv MPI_ROOT

env | grep MKL
env | grep UTILS

rm -rf build
mkdir build
cd build

cmake -DCMAKE_INSTALL_PREFIX=$HOME/Software//intel-2022.3.0/mpich-4.0.2/gronor/23.00 -DOPENACC=ON -DCUSOLVERJ=ON -DOPENMP=ON ../

make -j 12

make install

