#!/usr/bin/tcsh

module purge

module load cmake intel mpich gronor molcas mkl ga java

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx
unsetenv MPI_ROOT

env | grep MKL
env | grep UTILS
env | grep JAVA

rm -rf build_intel
mkdir build_intel
cd build_intel

cmake -DGUI=ON -DOPENMP=ON -DAVX512=ON -DCMAKE_INSTALL_PREFIX=$HOME/Software/intel-2022.3.0/mpich-4.0.3/gronor/24.0 ../

make -j 12

make install
