#!/usr/bin/tcsh

module purge
module load nvhpc/24.01 mpich/4.1.3 cmake 

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx
unsetenv MPI_ROOT

env | grep MKL
env | grep UTILS

rm -rf build_nvhpc
mkdir build_nvhpc
cd build_nvhpc

cmake -DACC=ON -DCUSOLVERJ=ON -DCMAKE_INSTALL_PREFIX=$HOME/Software/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION/gronor/24.00 ../

make -j 12

make install
