#!/bin/bash

module use /home/qq/coen/modules
module load compilers/nvmpi

export PATH=/home/programes/qq/cmake-3.18/bin:$PATH
export CUDA_MPS_PIPE_DIRECTORY=$HOME/log
export CUDA_MPS_LOG_DIRECTORY=$HOME/log
rm -rf build

mkdir build
cd build

if(! $?SOFTWARE ) setenv SOFTWARE $HOME/Software

cmake FC=mpif90 CC=mpicc -DMPI=ON -DOPENACC=ON -DCUDA=ON -DCUSOLVER=ON -DCUSOLVERJ=ON -DCMAKE_INSTALL_PREFIX=$SOFTWARE/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../

make -j 12
