#!/bin/tcsh

module load cmake nvhpc mpich

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx
unsetenv MPI_ROOT

rm -rf build
mkdir build
cd build

cmake -DOPENACC=ON -DCUSOLVERJ=ON -DCMAKE_INSTALL_PREFIX=$HOME/Software/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../

make -j 6
make install
