#!/bin/tcsh

module load cmake nvhpc mpich

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx
unsetenv MPI_ROOT

rm -rf build
mkdir build
cd build

if(! $?SOFTWARE ) setenv SOFTWARE $HOME/Software

cmake -DOPENACC=ON -DCUSOLVERJ=ON -DCMAKE_INSTALL_PREFIX=$SOFTWARE/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../

make -j 6
make install
