#!/usr/bin/tcsh

module load cmake
module load nvhpc
module load spectrum-mpi
module load cuda

module list

unsetenv MPI_ROOT

setenv FC mpif90
setenv CC mpicc
setenv CXX mpicxx

rm -rf build_summit
mkdir build_summit
cd build_summit

if(! $?SOFTWARE ) setenv SOFTWARE $HOME/Software 

cmake FC=mpif90 CC=mpicc CXX=mpicxx -DCMAKE_INSTALL_PREFIX=$SOFTWARE/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION -DACC=ON -DCUSOLVERJ=ON ../

make -j 16

make install
