#!/usr/bin/bash

module load CMake
module load NVHPC/21.9
module load CUDA
module list

export FC=mpif90
export CC=mpicc
export CXX=mpic++

rm -rf build
mkdir build
cd build

if(! $?SOFTWARE ) setenv SOFTWARE $HOME/Software

cmake -DOPENACC=ON -DCUSOLVERJ=ON  -DCMAKE_INSTALL_PREFIX=$SOFTWARE/$LMOD_FAMILY_COMPILER-$LMOD_FAMILY_COMPILER_VERSION/$LMOD_FAMILY_MPI-$LMOD_FAMILY_MPI_VERSION ../

make -j 12
