#!/usr/bin/tcsh
setenv MOLCAS_NPROCS 58
pymolcas -clean etheneA.input > etheneA.output
pymolcas -clean etheneD.input > etheneD.output
common_basis < etheneCB.input
touch TRAINT
setenv MOLCAS_MEM 4096
setenv MOLCAS_NPROCS 8
pymolcas -clean etheneM.input > etheneM.output
cat _CHMOT0 _CHMOT2 _CHMOT3 _CHMOT4 _CHMOT5 _CHMOT6 _CHMOT7 _CHMOT8 > _CHMOT1
rdcho 8
rdtraint < etheneCB.input
mpirun -n 36 gronor ethene_test


